apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-stage
  namespace: argocd
spec:
  destination:
    namespace: backend-stagee
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: cluster/overlay/stage
    repoURL: 'https://github.com/kgshukla/gitops.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
