apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-test
  namespace: argocd
spec:
  destination:
    namespace: backend-test
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: cluster/overlay/test
    repoURL: 'https://github.com/kgshukla/gitops.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
